*** Starting uWSGI 2.0.20 (64bit) on [Thu Apr  7 21:24:31 2022] ***
compiled with version: 7.5.0 on 07 April 2022 20:53:56
os: Linux-4.15.0 #1 SMP Tue Jun 9 12:58:54 MSK 2020
nodename: greezy.io
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/greezy/public_html/Greezy
detected binary path: /home/greezy/public_html/Greezy/greezyenv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 62987
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address greezy.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.0 (default, Dec  9 2021, 17:53:27)  [GCC 8.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x555db1e08e10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437520 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x555db1e08e10 pid: 23027 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 23027)
spawned uWSGI worker 1 (pid: 23029, cores: 1)
spawned uWSGI worker 2 (pid: 23030, cores: 1)
spawned uWSGI worker 3 (pid: 23031, cores: 1)
spawned uWSGI worker 4 (pid: 23032, cores: 1)
spawned uWSGI worker 5 (pid: 23033, cores: 1)
[pid: 23031|app: 0|req: 1/1] 43.251.253.140 () {46 vars in 806 bytes} [Thu Apr  7 21:24:48 2022] GET / => generated 218 bytes in 5 msecs (HTTP/1.1 302) 3 headers in 101 bytes (1 switches on core 0)
[pid: 23032|app: 0|req: 1/2] 43.251.253.140 () {46 vars in 816 bytes} [Thu Apr  7 21:24:48 2022] GET /login => generated 4489 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 1/3] 43.251.253.140 () {44 vars in 703 bytes} [Thu Apr  7 21:24:48 2022] GET /static/css/login.css => generated 6310 bytes in 5 msecs via sendfile() (HTTP/1.1 200) 6 headers in 237 bytes (0 switches on core 0)
[pid: 23030|app: 0|req: 1/4] 43.251.253.140 () {44 vars in 753 bytes} [Thu Apr  7 21:24:50 2022] GET /static/images/logo.png => generated 7670 bytes in 7 msecs via sendfile() (HTTP/1.1 200) 6 headers in 222 bytes (0 switches on core 0)
[pid: 23033|app: 0|req: 1/5] 43.251.253.140 () {44 vars in 731 bytes} [Thu Apr  7 21:24:52 2022] GET /favicon.ico => generated 232 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[2022-04-07 21:25:06,173] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.coins

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./app.py", line 174, in login
    user = User.query.filter_by(email=email, password=password).first()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2819, in first
    return self.limit(1)._iter().first()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.coins
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.first_name AS user_first_name, user.last_name AS user_last_name, user.email AS user_email, user.password AS user_password, user.phone AS user_phone, user.street_address AS user_street_address, user.zip_code AS user_zip_code, user.city AS user_city, user.cryptocurrency AS user_cryptocurrency, user.wallet AS user_wallet, user.coins AS user_coins, user.kyc_verified AS user_kyc_verified, user.profit AS user_profit 
FROM user 
WHERE user.email = ? AND user.password = ?
 LIMIT ? OFFSET ?]
[parameters: ('fgdgs@sdfas.com', 'safdfsaf', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[pid: 23029|app: 0|req: 2/6] 43.251.253.140 () {54 vars in 1004 bytes} [Thu Apr  7 21:25:06 2022] POST /login => generated 290 bytes in 74 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
[2022-04-07 21:25:45,543] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.coins

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./app.py", line 174, in login
    user = User.query.filter_by(email=email, password=password).first()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2819, in first
    return self.limit(1)._iter().first()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.coins
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.first_name AS user_first_name, user.last_name AS user_last_name, user.email AS user_email, user.password AS user_password, user.phone AS user_phone, user.street_address AS user_street_address, user.zip_code AS user_zip_code, user.city AS user_city, user.cryptocurrency AS user_cryptocurrency, user.wallet AS user_wallet, user.coins AS user_coins, user.kyc_verified AS user_kyc_verified, user.profit AS user_profit 
FROM user 
WHERE user.email = ? AND user.password = ?
 LIMIT ? OFFSET ?]
[parameters: ('fgdgs@sdfas.com', 'safdfsaf', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[pid: 23029|app: 0|req: 3/7] 43.251.253.140 () {54 vars in 1004 bytes} [Thu Apr  7 21:25:45 2022] POST /login => generated 290 bytes in 6 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 4/8] 43.251.253.140 () {54 vars in 1004 bytes} [Thu Apr  7 21:29:43 2022] POST /login => generated 4603 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 171 bytes (2 switches on core 0)
[pid: 23033|app: 0|req: 2/9] 43.251.253.140 () {46 vars in 758 bytes} [Thu Apr  7 21:29:43 2022] GET /static/css/login.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 3 headers in 140 bytes (1 switches on core 0)
[pid: 23033|app: 0|req: 3/10] 43.251.253.140 () {46 vars in 808 bytes} [Thu Apr  7 21:29:43 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 5/11] 43.251.253.140 () {44 vars in 775 bytes} [Thu Apr  7 21:30:28 2022] GET / => generated 218 bytes in 1 msecs (HTTP/1.1 302) 3 headers in 101 bytes (1 switches on core 0)
[pid: 23031|app: 0|req: 2/12] 43.251.253.140 () {44 vars in 785 bytes} [Thu Apr  7 21:30:29 2022] GET /login => generated 4489 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 6/13] 43.251.253.140 () {46 vars in 808 bytes} [Thu Apr  7 21:30:29 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (0 switches on core 0)
[pid: 23032|app: 0|req: 2/14] 43.251.253.140 () {46 vars in 758 bytes} [Thu Apr  7 21:30:29 2022] GET /static/css/login.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 140 bytes (0 switches on core 0)
[pid: 23033|app: 0|req: 4/15] 43.251.253.140 () {44 vars in 775 bytes} [Thu Apr  7 21:30:55 2022] GET / => generated 218 bytes in 1 msecs (HTTP/1.1 302) 3 headers in 101 bytes (1 switches on core 0)
[pid: 23030|app: 0|req: 2/16] 43.251.253.140 () {44 vars in 785 bytes} [Thu Apr  7 21:30:55 2022] GET /login => generated 4489 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 7/17] 43.251.253.140 () {46 vars in 758 bytes} [Thu Apr  7 21:30:55 2022] GET /static/css/login.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 140 bytes (0 switches on core 0)
[pid: 23033|app: 0|req: 5/18] 43.251.253.140 () {46 vars in 808 bytes} [Thu Apr  7 21:30:55 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (0 switches on core 0)
[pid: 23032|app: 0|req: 3/19] 43.251.253.140 () {54 vars in 1004 bytes} [Thu Apr  7 21:31:06 2022] POST /login => generated 4603 bytes in 36 msecs (HTTP/1.1 200) 3 headers in 171 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 8/20] 43.251.253.140 () {46 vars in 758 bytes} [Thu Apr  7 21:31:07 2022] GET /static/css/login.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 140 bytes (0 switches on core 0)
[pid: 23030|app: 0|req: 3/21] 43.251.253.140 () {46 vars in 808 bytes} [Thu Apr  7 21:31:07 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (0 switches on core 0)
[pid: 23033|app: 0|req: 6/22] 43.251.253.140 () {46 vars in 827 bytes} [Thu Apr  7 21:31:11 2022] GET /signup => generated 5918 bytes in 12 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 23031|app: 0|req: 3/23] 43.251.253.140 () {46 vars in 759 bytes} [Thu Apr  7 21:31:11 2022] GET /static/css/login.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 3 headers in 140 bytes (0 switches on core 0)
[pid: 23030|app: 0|req: 4/24] 43.251.253.140 () {46 vars in 809 bytes} [Thu Apr  7 21:31:11 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (0 switches on core 0)
[pid: 23029|app: 0|req: 9/25] 43.251.253.140 () {54 vars in 1009 bytes} [Thu Apr  7 21:31:38 2022] POST /signup => generated 6037 bytes in 21 msecs (HTTP/1.1 200) 3 headers in 171 bytes (1 switches on core 0)
[pid: 23030|app: 0|req: 5/26] 43.251.253.140 () {46 vars in 809 bytes} [Thu Apr  7 21:31:38 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (0 switches on core 0)
[pid: 23031|app: 0|req: 4/27] 43.251.253.140 () {46 vars in 759 bytes} [Thu Apr  7 21:31:38 2022] GET /static/css/login.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 140 bytes (0 switches on core 0)
[pid: 23031|app: 0|req: 5/28] 43.251.253.140 () {46 vars in 826 bytes} [Thu Apr  7 21:31:46 2022] GET /login => generated 4489 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 23030|app: 0|req: 6/29] 43.251.253.140 () {46 vars in 808 bytes} [Thu Apr  7 21:31:46 2022] GET /static/images/logo.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 139 bytes (0 switches on core 0)
[pid: 23032|app: 0|req: 4/30] 43.251.253.140 () {46 vars in 758 bytes} [Thu Apr  7 21:31:46 2022] GET /static/css/login.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 140 bytes (0 switches on core 0)
[pid: 23033|app: 0|req: 7/31] 43.251.253.140 () {44 vars in 753 bytes} [Thu Apr  7 21:31:48 2022] GET /static/images/logo.png => generated 7670 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 6 headers in 222 bytes (0 switches on core 0)
[pid: 23031|app: 0|req: 6/32] 43.251.253.140 () {54 vars in 1004 bytes} [Thu Apr  7 21:31:57 2022] POST /login => generated 216 bytes in 34 msecs (HTTP/1.1 302) 5 headers in 207 bytes (1 switches on core 0)
[2022-04-07 21:31:58,234] ERROR in app: Exception on /home [GET]
Traceback (most recent call last):
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./app.py", line 211, in home
    fiatBalance = round(current_user.getFiatBalance())
  File "./app.py", line 99, in getFiatBalance
    i = float(auth.get_account(self.getAccountID(fiatName))['available'])
  File "./app.py", line 92, in getAccountID
    for account in auth.get_accounts():
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/cbpro/authenticated_client.py", line 89, in get_accounts
    return self.get_account('')
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/cbpro/authenticated_client.py", line 61, in get_account
    return self._send_message('get', '/accounts/' + account_id)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/cbpro/public_client.py", line 268, in _send_message
    r = self.session.request(method, url, params=params, data=data,
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/requests/sessions.py", line 397, in prepare_request
    p.prepare(
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/requests/models.py", line 543, in prepare_auth
    r = auth(self)
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/cbpro/cbpro_auth.py", line 19, in __call__
    request.headers.update(get_auth_headers(timestamp, message,
  File "/home/greezy/public_html/Greezy/greezyenv/lib/python3.8/site-packages/cbpro/cbpro_auth.py", line 28, in get_auth_headers
    hmac_key = base64.b64decode(secret_key)
  File "/usr/lib/python3.8/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.8/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
[pid: 23029|app: 0|req: 10/33] 43.251.253.140 () {48 vars in 917 bytes} [Thu Apr  7 21:31:58 2022] GET /home => generated 290 bytes in 15 msecs (HTTP/1.1 500) 3 headers in 113 bytes (1 switches on core 0)
[pid: 23029|app: 0|req: 11/34] 103.73.102.74 () {40 vars in 486 bytes} [Thu Apr  7 21:40:59 2022] GET / => generated 218 bytes in 1 msecs (HTTP/1.1 302) 3 headers in 101 bytes (1 switches on core 0)
[pid: 23031|app: 0|req: 7/35] 103.73.102.74 () {40 vars in 496 bytes} [Thu Apr  7 21:41:00 2022] GET /login => generated 4489 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
